https://github.com/dbabichenko/python_for_data_and_analytics/tree/master/12%20-%20Classification

In [1]:
# Required Python Machine learning Packages
import pandas as pd
import numpy as np
import operator

# To split the dataset into train and test datasets
from sklearn.model_selection import train_test_split

# Classifiers
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, export_graphviz

from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.feature_selection import RFE
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier

# To calculate the accuracy score of the model
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def label_encode(df, columns):
    for col in columns:
        le = LabelEncoder()
        col_values_unique = list(df[col].unique())
        le_fitted = le.fit(col_values_unique)
 
        col_values = list(df[col].values)
        #le.classes_
        col_values_transformed = le.transform(col_values)
        df[col] = col_values_transformed

In [3]:
def classify(predictors, response, classifier = 'svm', kern='rbf', neighbors=3, kfolds=0, report=False, features_select=0):        
    # split X and y into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(predictors, response, test_size=0.20, random_state=1)

    
    if classifier == 'nb':
        cl = GaussianNB() # instantiate model
        msg = 'Naive Bayes'
    elif classifier == 'svm':
        cl = svm.SVC(kernel=kern) # instantiate model
        msg = 'SVM with ' + kern + ' kernel'
    elif classifier == 'knn':
        cl = KNeighborsRegressor(n_neighbors=neighbors)
        msg = 'KNN with k=' + str(neighbors)
    elif classifier == 'rf':
        # Instantiate model with  decision trees
        # Note that the number of decision trees is denoted
        # using the neighbors parameter, which is set to 3 by default
        cl = RandomForestRegressor(n_estimators = 1000, random_state = 42)
        msg = 'Random Forest with ' + str(neighbors) + ' decision trees'
    elif classifier == 'dtree':
        cl = DecisionTreeClassifier(min_samples_split=20, random_state=99)
        msg = 'Decision tree'
    elif classifier == 'logisticregression':
        cl = LogisticRegression()
        msg = 'Logistic Regression'
        
    model = cl.fit(X_train, y_train)
    y_pred_class = model.predict(X_test)
    print(msg + ' model accuracy score: ', metrics.accuracy_score(y_test, y_pred_class.round()))
    
    if kfolds > 0:
        # Perform k-fold cross validation
        scores = cross_val_score(model, predictors, response, cv=kfolds)
        print('Cross-validated score:', scores.mean())
    
    if report == True:
        print('Confusion matrix')
        print(metrics.confusion_matrix(y_test, y_pred_class)) # confusion matrix
        print('Classification report')
        target_names=['low','med','high']
        print(metrics.classification_report(y_test, y_pred_class, target_names=target_names))
        
        print('______________________________')
    
    if features_select > 0:
        test = SelectKBest(score_func=chi2, k=features_select)
        fit = test.fit(predictors, response)
        
        # summarize scores
        np.set_printoptions(precision=3)
        # print(fit.scores_)
        features_scores = {}
        for i in range(0, len(predictors.columns)):
            features_scores[predictors.columns[i]] = fit.scores_[i]
            
        # print(features_scores)
        sorted_features_scores = sorted(features_scores.items(), key=operator.itemgetter(1))
        print(sorted_features_scores[-5:])        

In [4]:
def decompose(predictors):
    # feature extraction
    pca = PCA(n_components=3)
    fit = pca.fit(predictors)
    
    # summarize components
    # print(fit.explained_variance_ratio_)
    # print(fit.components_)
    return pd.DataFrame(fit.components_)

In [5]:
df = pd.read_csv("311TrimmedGrouped.csv")
df.head()

Unnamed: 0  REQUEST_ID           CREATED_ON REQUEST_TYPE REQUEST_ORIGIN  \
0          13      205276  2017-12-31T13:42:00     Potholes        Website   
1          75      205180  2017-12-29T17:45:00     Potholes        Website   
2          96      205151  2017-12-29T14:58:00     Potholes    Call Center   
3         112      205130  2017-12-29T14:03:00     Potholes    Call Center   
4         133      205098  2017-12-29T12:40:00     Potholes    Call Center   

   STATUS                DEPARTMENT   NEIGHBORHOOD  COUNCIL_DISTRICT  WARD  \
0       1  DPW - Street Maintenance      Beechview               4.0  19.0   
1       1  DPW - Street Maintenance     Manchester               6.0  21.0   
2       1  DPW - Street Maintenance  Regent Square               9.0  14.0   
3       1  DPW - Street Maintenance      Brookline               4.0  19.0   
4       1  DPW - Street Maintenance  Lincoln Place               5.0  31.0   

       ...        daily.temperatureMinTime  daily.time  daily.uvIndex  \
0      ...                      1514721600  1514696400              1   
1      ...                      1514541600  1514523600              1   
2      ...                      1514541600  1514523600              1   
3      ...                      1514541600  1514523600              1   
4      ...                      1514541600  1514523600              1   

   daily.uvIndexTime daily.visibility  daily.windBearing  daily.windGust  \
0         1514732400             9.10                261            5.37   
1         1514559600             8.58                253            8.96   
2         1514559600             8.28                252            8.98   
3         1514559600             8.59                253            9.22   
4         1514559600             8.32                252            9.37   

  daily.windGustTime  daily.windSpeed  REQUEST_GROUP  
0         1514696400             0.56          Roads  
1         1514577600             1.31          Roads  
2         1514577600             1.26          Roads  
3         1514577600             1.30          Roads  
4         1514577600             1.29          Roads  

[5 rows x 75 columns]

In [6]:
df.fillna(0, inplace=True) #fill zero instances of weather
df = df.reset_index()

In [7]:
df.columns

Index(['index', 'Unnamed: 0', 'REQUEST_ID', 'CREATED_ON', 'REQUEST_TYPE',
       'REQUEST_ORIGIN', 'STATUS', 'DEPARTMENT', 'NEIGHBORHOOD',
       'COUNCIL_DISTRICT', 'WARD', 'TRACT', 'PUBLIC_WORKS_DIVISION',
       'PLI_DIVISION', 'POLICE_ZONE', 'FIRE_ZONE', 'X', 'Y', 'GEO_ACCURACY',
       'current.apparentTemperature', 'current.cloudCover', 'current.dewPoint',
       'current.humidity', 'current.icon', 'current.precipIntensity',
       'current.precipProbability', 'current.precipType', 'current.pressure',
       'current.summary', 'current.temperature', 'current.time',
       'current.uvIndex', 'current.visibility', 'current.windBearing',
       'current.windGust', 'current.windSpeed',
       'daily.apparentTemperatureHigh', 'daily.apparentTemperatureHighTime',
       'daily.apparentTemperatureLow', 'daily.apparentTemperatureLowTime',
       'daily.apparentTemperatureMax', 'daily.apparentTemperatureMaxTime',
       'daily.apparentTemperatureMin', 'daily.apparentTemperatureMinTime',
 

In [8]:
df.corr()

index  Unnamed: 0  REQUEST_ID    STATUS  \
index                              1.000000   -0.051815    0.052628 -0.049882   
Unnamed: 0                        -0.051815    1.000000   -0.999832 -0.009968   
REQUEST_ID                         0.052628   -0.999832    1.000000  0.010486   
STATUS                            -0.049882   -0.009968    0.010486  1.000000   
COUNCIL_DISTRICT                  -0.071076    0.041724   -0.041505  0.005129   
WARD                               0.009420   -0.029995    0.029464  0.004965   
TRACT                             -0.009921   -0.012563    0.012534  0.008233   
PUBLIC_WORKS_DIVISION             -0.028873   -0.001909    0.001780 -0.025449   
PLI_DIVISION                       0.009420   -0.029995    0.029464  0.004965   
POLICE_ZONE                       -0.075824    0.015102   -0.015286 -0.022022   
X                                 -0.059970    0.040363   -0.040154  0.003031   
Y                                  0.026881   -0.001772    0.001893  0.024175   
current.apparentTemperature       -0.117956   -0.221854    0.209526 -0.022072   
current.cloudCover                 0.043788    0.219047   -0.214991  0.010790   
current.dewPoint                  -0.105901   -0.252950    0.240115 -0.014588   
current.humidity                   0.006891   -0.129303    0.125623  0.015455   
current.precipIntensity           -0.017897    0.068511   -0.068115  0.003919   
current.precipProbability         -0.014544    0.178832   -0.177064  0.007254   
current.pressure                   0.049646   -0.215991    0.219260 -0.003600   
current.temperature               -0.117159   -0.218763    0.206438 -0.021850   
current.time                       0.053674   -0.996814    0.997775  0.012227   
current.uvIndex                   -0.046340    0.004025   -0.008540 -0.019767   
current.visibility                -0.059624    0.017910   -0.017134 -0.012931   
current.windBearing                0.027995    0.136984   -0.133651  0.005802   
current.windGust                  -0.006352    0.298270   -0.291795 -0.004430   
current.windSpeed                 -0.006610    0.335240   -0.327501  0.000493   
daily.apparentTemperatureHigh     -0.127408   -0.260271    0.247182 -0.016925   
daily.apparentTemperatureHighTime  0.053675   -0.996817    0.997774  0.012244   
daily.apparentTemperatureLow      -0.117774   -0.235579    0.222719 -0.018935   
daily.apparentTemperatureLowTime   0.053700   -0.996825    0.997782  0.012258   
...                                     ...         ...         ...       ...   
daily.apparentTemperatureMin      -0.111831   -0.250201    0.236886 -0.018414   
daily.apparentTemperatureMinTime   0.053694   -0.996798    0.997763  0.012299   
daily.cloudCover                   0.043304    0.260857   -0.256250  0.010364   
daily.dewPoint                    -0.104506   -0.267445    0.254356 -0.014939   
daily.humidity                     0.021599   -0.156085    0.152819  0.002835   
daily.moonPhase                   -0.042461    0.013021   -0.014604  0.005291   
daily.precipAccumulation           0.086891    0.154749   -0.153436  0.004531   
daily.precipIntensity             -0.058433    0.101483   -0.101833  0.010197   
daily.precipIntensityMax          -0.057827    0.057184   -0.059325  0.005452   
daily.precipIntensityMaxTime      -0.009798    0.154768   -0.154193  0.010605   
daily.precipProbability           -0.072147    0.237420   -0.236794  0.007702   
daily.pressure                     0.062838   -0.226059    0.229555 -0.007466   
daily.sunriseTime                  0.053731   -0.996805    0.997769  0.012265   
daily.sunsetTime                   0.053625   -0.996831    0.997784  0.012255   
daily.temperatureHigh             -0.131327   -0.256318    0.243279 -0.016284   
daily.temperatureHighTime          0.053697   -0.996822    0.997777  0.012243   
daily.temperatureLow              -0.117273   -0.224238    0.211381 -0.018497   
daily.temperatureLowTime           0.053694   -0.996827    0.997784  

In [9]:
# define X and y
X = df[['current.cloudCover', 'current.humidity',
       'current.icon', 'current.precipIntensity', 'current.precipProbability',
       'current.precipType', 'current.summary',
       'current.temperature', 'current.uvIndex',
       'current.visibility', 'current.windBearing', 'current.windGust',
       'current.windSpeed', 'daily.cloudCover', 'daily.humidity', 'daily.icon', 'daily.moonPhase',
       'daily.precipAccumulation', 'daily.precipIntensity', 'daily.precipIntensityMax', 
       'daily.precipProbability', 'daily.precipType', 'daily.pressure',
       'daily.summary', 'daily.temperatureHigh',  
     'daily.uvIndex', 'daily.visibility',
       'daily.windBearing', 'daily.windGust', 'daily.windSpeed']]
label_encode(X, X.columns.values)

# y = df[['NEIGHBORHOOD']]
# y = df['DEPARTMENT']
y = df[['REQUEST_GROUP']]  

label_encode(y, y.columns.values)
# y = y['REQUEST_GROUP']

C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.


In [10]:
X.corr()

current.cloudCover  current.humidity  current.icon  \
current.cloudCover                   1.000000          0.219752      0.612156   
current.humidity                     0.219752          1.000000      0.279921   
current.icon                         0.612156          0.279921      1.000000   
current.precipIntensity              0.284193          0.244166      0.417408   
current.precipProbability            0.433131          0.331615      0.583065   
current.precipType                   0.398788          0.212861      0.415255   
current.summary                      0.687319          0.066784      0.516385   
current.temperature                 -0.172083         -0.002270     -0.005653   
current.uvIndex                     -0.143001         -0.521086     -0.098155   
current.visibility                  -0.230114         -0.407161     -0.250693   
current.windBearing                  0.238384         -0.195982      0.097108   
current.windGust                     0.292637         -0.482247      0.103641   
current.windSpeed                    0.310010         -0.418396      0.123151   
daily.cloudCover                     0.820560          0.239209      0.501930   
daily.humidity                       0.408556          0.621106      0.372874   
daily.icon                           0.127747          0.139472      0.244184   
daily.moonPhase                      0.048545          0.066863      0.011893   
daily.precipAccumulation             0.167995          0.032246      0.217042   
daily.precipIntensity                0.271645          0.233867      0.340680   
daily.precipIntensityMax             0.208139          0.207661      0.279126   
daily.precipProbability              0.388356          0.244955      0.385038   
daily.precipType                     0.396291          0.150114      0.327423   
daily.pressure                      -0.290961         -0.239394     -0.272930   
daily.summary                        0.126212          0.125117      0.200444   
daily.temperatureHigh               -0.369651          0.164234     -0.119255   
daily.uvIndex                       -0.472735         -0.024223     -0.230791   
daily.visibility                    -0.323801         -0.292153     -0.245126   
daily.windBearing                    0.075511         -0.039152      0.038444   
daily.windGust                       0.213596         -0.179113      0.120122   
daily.windSpeed                      0.278524         -0.189341      0.129333   

                           current.precipIntensity  current.precipProbability  \
current.cloudCover                        0.284193                   0.433131   
current.humidity                          0.244166                   0.331615   
current.icon                              0.417408                   0.583065   
current.precipIntensity                   1.000000                   0.773073   
current.precipProbability                 0.773073                   1.000000   
current.precipType                        0.284258                   0.549441   
current.summary                           0.096188                   0.014156   
current.temperature                       0.061160                   0.005860   
current.uvIndex                          -0.035435                  -0.064205   
current.visibility                       -0.224758                  -0.287504   
current.windBearing                      -0.049052                   0.000510   
current.windGust                          0.019376                   0.103799   
current.windSpeed                         0.030401                   0.135425   
daily.cloudCover                          0.263698                   0.431936   
daily.humidity                            0.283822                   0.394530   
daily.icon                                0.276836                   0.284381   
daily.moonPhase                           0.043080                   0.022104   
daily.precipAccumulation                 -0.015246       

In [13]:
#classify(X, y, classifier='nb', kfolds=10, report=False, features_select=3)
# classify(X, y, classifier='svm', kern='rbf', kfolds=10, report=False, features_select=3)
#X_pca = decompose(X)
#classify(X_pca, y, classifier='svm', kern='rbf', kfolds=10, report=False, features_select=3)
#print(X_pca.shape)
# classify(X, y, classifier='svm', kern='linear', kfolds=10, report=True)
# classify(X, y, classifier='svm', kern='poly', kfolds=10, report=True)
# classify(X, y, classifier='knn', neighbors=3, kfolds=10)
# classify(X, y, classifier='knn', neighbors=5, kfolds=10)
# classify(X, y, classifier='knn', neighbors=7)
# classify(X, y, classifier='rf', neighbors=1000, kfolds=10)
# classify(X, y, classifier='rf', neighbors=2000)
# classify(X, y, classifier='dtree', kfolds=10)
classify(X, y, classifier='logisticregression', kfolds=10, report=True, features_select=5)

C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Logistic Regression model accuracy score:  0.393658471046621


C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A 

Cross-validated score: 0.34792896938601936
Confusion matrix
[[   0    0    0   33  314   18    0]
 [   0    0    0   65  759   56    0]
 [   0    0    0   23  119    7    0]
 [   0    0    0   95 1435  114    0]
 [   0    0    0  147 2482  141    0]
 [   0    0    0   70  774  353    0]
 [   0    0    0   23  409    6    0]]
Classification report
             precision    recall  f1-score   support

        low       0.00      0.00      0.00       365
        med       0.00      0.00      0.00       880
       high       0.00      0.00      0.00       149

avg / total       0.27      0.39      0.28      7443

______________________________
[('daily.precipIntensityMax', 160104.58115881545), ('current.windGust', 222673.68017020245), ('daily.precipAccumulation', 362324.48368737136), ('current.temperature', 1206519.9106679899), ('daily.temperatureHigh', 1616820.509686216)]


C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 7, does not match size of target_names, 3
  .format(len(labels), len(target_names))
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [14]:
classify(X, y, classifier='nb', kfolds=10, report=True, features_select=5)

C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A 

Naive Bayes model accuracy score:  0.2883246002955797


C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A 

Cross-validated score: 0.24838012090811165
Confusion matrix
[[  27    3    0   42  111   18  164]
 [  49    3    0  113  304  122  289]
 [  10    0    0   19   45   12   63]
 [  98    1    0  189  511  225  620]
 [ 122    7    0  271 1208  307  855]
 [  38    1    0   93  272  462  331]
 [  26    3    0   36  107    9  257]]
Classification report
             precision    recall  f1-score   support

        low       0.07      0.07      0.07       365
        med       0.17      0.00      0.01       880
       high       0.00      0.00      0.00       149

avg / total       0.32      0.29      0.28      7443

______________________________
[('daily.precipIntensityMax', 160104.58115881545), ('current.windGust', 222673.68017020245), ('daily.precipAccumulation', 362324.48368737136), ('current.temperature', 1206519.9106679899), ('daily.temperatureHigh', 1616820.509686216)]


C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 7, does not match size of target_names, 3
  .format(len(labels), len(target_names))
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [15]:
classify(X, y, classifier='dtree', kfolds=10, report=True, features_select=5)

Decision tree model accuracy score:  0.3837162434502217
Cross-validated score: 0.21509366425934867
Confusion matrix
[[  16   39    3   89  167   32   19]
 [  16  143    3  206  356  120   36]
 [   5   22    7   32   57   20    6]
 [  42  155   11  647  533  187   69]
 [  56  288   21  520 1526  259  100]
 [  29  100    6  207  342  478   35]
 [  19   46    1  101  177   55   39]]
Classification report
             precision    recall  f1-score   support

        low       0.09      0.04      0.06       365
        med       0.18      0.16      0.17       880
       high       0.13      0.05      0.07       149

avg / total       0.36      0.38      0.37      7443

______________________________
[('daily.precipIntensityMax', 160104.58115881545), ('current.windGust', 222673.68017020245), ('daily.precipAccumulation', 362324.48368737136), ('current.temperature', 1206519.9106679899), ('daily.temperatureHigh', 1616820.509686216)]


C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 7, does not match size of target_names, 3
  .format(len(labels), len(target_names))


In [16]:
#classify(X, y, classifier='rf', kfolds=10, report=True, features_select=5)

In [19]:
classify(X, y, classifier='rf', neighbors=1000, kfolds=5, report=True)

C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:28: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Random Forest with 1000 decision trees model accuracy score:  0.38479107886604863


C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\boblutz\AppData\Local\Continuum\anaconda3\l

Cross-validated score: -1.7465609382341178
Confusion matrix


ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [ ]:
classify(X, y, classifier='knn', neighbors=7, kfolds=10, report=True, features_select=5)

In [ ]:
classify(X, y, classifier='knn', neighbors=5, kfolds=10, report=True, features_select=5)

In [ ]:
classify(X, y, classifier='knn', neighbors=3, kfolds=10, report=True, features_select=5)

In [ ]:
# classify(X, y, classifier='svm', kern='poly', kfolds=10, report=True)
# classify(X, y, classifier='svm', kern='linear', kfolds=10, report=True)

In [ ]:
classify(X, y, classifier='svm', kern='rbf', kfolds=10, report=True, features_select=5)

In [ ]:
classify(X, y, classifier='svm', kern='ply', kfolds=10, report=True, features_select=5)

In [ ]:
X_pca = decompose(X)
classify(X_pca, y, classifier='svm', kern='rbf',kfolds=10, report=True, features_select=5)
print(X_pca.shape)